### ISSUE TITLE
I ran the script and got an error. How can I fix it?

### ISSUE THREAD

**Issue by Shiratsuyu1** [siddhartamukherjee/NEU-SURFACE-DEFECT#4]
The error message is as follows, really appreciate your help.

Traceback (most recent call last):
  File "D:/NEU-DET-Steel-Surface-Defect-Detection-master/FPN_Resnet_Train.py", line 31, in <module>
    model_trainer = Trainer(model, lr, epochs, path)
  File "D:\NEU-DET-Steel-Surface-Defect-Detection-master\Utilities\Trainer.py", line 54, in __init__
    checkpoint = torch.load(self.PATH)
  File "C:\Users\pc\.conda\envs\env\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\pc\.conda\envs\env\lib\site-packages\torch\serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

Process finished with exit code 1

**Comment by thesuncool** [comment]
> The error message is as follows, really appreciate your help.
> 
> Traceback (most recent call last): File "D:/NEU-DET-Steel-Surface-Defect-Detection-master/FPN_Resnet_Train.py", line 31, in model_trainer = Trainer(model, lr, epochs, path) File "D:\NEU-DET-Steel-Surface-Defect-Detection-master\Utilities\Trainer.py", line 54, in **init** checkpoint = torch.load(self.PATH) File "C:\Users\pc.conda\envs\env\lib\site-packages\torch\serialization.py", line 593, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "C:\Users\pc.conda\envs\env\lib\site-packages\torch\serialization.py", line 762, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'v'.
> 
> Process finished with exit code 1

hello，I also encountered the same problem. Have you solved it？
